# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 937574dab7d79b112a32623da7e0895b43a31d79e18e3c9d356cc1964a4e0d972e9674a54797ee5288e24d88e34e3d0ce6553cfe8b02c7a13e13857b877ba7f3

test:
  secret_key_base: 580df326eff856fbd45ace328953dca50d724df0dd51858c00f8059b43cd1840d8ede9bd90b805e0902586ca6e1a8c41da11ce17e5c2dd554783eb64ca461b70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
